apiVersion: gcp.multivault.crossplane.io/v1alpha1
kind: VaultCluster
metadata:
  name: vault-on-gke-cluster
spec:
  compositionSelector:
    matchLabels:
      provider: GCP
  id: vault-on-gke-cluster
  projectID: crossplane-playground
  parameters:
    nodes:
      count: 1
      size: small
  writeConnectionSecretToRef:
    name: cluster-conn
