apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vaultongkes.gcp.multivault.crossplane.io
  annotations:
    upbound.io/ui-schema: |-
      ---
      configSections:
      - title: Project ID
        description: Project ID of this Cluster
        items:
        - name: projectID
          controlType: singleInput
          type: string
          path: ".spec.projectID"
          title: Project ID
          description: Project ID of this Cluster that other objects will use to refer to it
          default: crossplane-playground
          validation:
          - required: true
            customError: Project ID is required.
      - title: Cluster Info
        description: Information about this cluster
        items:
        - name: id
          controlType: singleInput
          type: string
          path: ".spec.id"
          title: Cluster ID
          description: Cluster ID that other objects will use to refer to this cluster
          default: vault-on-gke-cluster
          validation:
          - required: true
            customError: Cluster ID is required.
        - name: writeSecretRef
          controlType: singleInput
          type: string
          path: ".spec.writeConnectionSecretToRef.name"
          title: Connection Secret Ref
          description: name of the secret to write to this namespace
          default: cluster-conn
          validation:
          - required: true
      - title: Cluster Nodes
        description: Enter information to size your cluster
        items:
        - name: clusterNodeCount
          controlType: singleInput
          type: integer
          path: ".spec.parameters.nodes.count"
          title: Node Count
          description: Number of nodes in the cluster
          default: 1
          validation:
          - minimum: 1
          - maximum: 100
          - required: true
            customError: Node count is required.
        - name: clusterNodeSize
          controlType: singleSelect
          path: ".spec.parameters.nodes.size"
          title: Node Size
          description: Desired node count, from 1 to 100.
          default: small
          enum:
          - small
          - medium
          - large
          validation:
          - required: true
            customError: Node size is required.
spec:
  claimNames:
    kind: VaultCluster
    plural: vaultclusters
  connectionSecretKeys:
  - kubeconfig
  group: gcp.multivault.crossplane.io
  names:
    kind: VaultOnGKE
    plural: vaultongkes
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this Cluster that other objects will use to refer to it.
              projectID:
                type: string
                description: Project ID of this Cluster that other objects will use to refer to it.
              parameters:
                type: object
                description: Cluster configuration parameters.
                properties:
                  nodes:
                    type: object
                    description: Cluster node configuration parameters.
                    properties:
                      count:
                        type: integer
                        description: Desired node count, from 1 to 100.
                      size:
                        type: string
                        description: Size of node.
                        enum:
                        - small
                        - medium
                        - large
                    required:
                    - count
                    - size
                required:
                - nodes
            required:
            - id
            - parameters
